eeeee proxy
MarinaShustova/Socks5-java- pull request #1
Opened 2018-12-30 20:37 UTC by MarinaShustova

2018-12-31 05:26 UTC, Aloomenon requested changes
Оставил несколько замечаний по коду.
Каждое из замечаний обсуждается и не обязательно к исправлению, если сможете меня в этом убедить.
Закрывать обсуждения по каждому из случаев не надо, я сделаю это сам.

2018-12-31 05:26 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Main.java
> +            Integer lport = Integer.parseInt(args[0]);
Стоит обработать NumberFormatException, т.к. ввод будет пользовательский.

2018-12-31 05:26 UTC, Aloomenon commented on MY_SOCKS/src/main/java/MessageParser.java
> +                int num_methods = (int)msg[1];
Есть https://google.github.io/styleguide/javaguide.html если вдруг собираетесь писать на Java, то стоит его придерживаться.

2018-12-31 05:26 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Forwarder.java
> +                    if (key.isValid() && key.isWritable()){
Мертвый код :<

2018-12-31 05:26 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Forwarder.java
> +            sc.close();
SocketChannel закрываем, а почему не закрываем ServerSocketChannel и DatagramChannel?

2018-12-31 09:08 UTC, MarinaShustova commented
@Aloomenon вроде всё поправила (в одном коммите), только немного по codestyle не поняла - слишком на си похоже, в этом проблема?

2018-12-31 09:48 UTC, Aloomenon requested changes

2018-12-31 09:48 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Forwarder.java
> +        }catch (Exception e){
А если не попадем в catch-блок, когда произойдет очистка ресурсов? в catch - происходит обработка исключения. Очистку лучше делать в finally-блоке. Также можно использовать try-with-resources.

2018-12-31 09:48 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Main.java
> +            Integer lport = Integer.parseInt(args[0]);
ок.

2018-12-31 09:50 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Forwarder.java
> +        }catch (Exception e){
> @Aloomenon вроде всё поправила (в одном коммите), только немного по codestyle не поняла - слишком на си похоже, в этом проблема?
Да. Там явно заиспользован стиль языка С. Если уж пишем на Java, то стоит придерживаться Java code style. Так код становится более ясным.

2019-01-02 18:03 UTC, MarinaShustova commented
@Aloomenon теперь сокеты должны закрываться всегда (надеюсь, то, что я делаю с udpsocket законно)

2019-01-03 05:49 UTC, Aloomenon commented on MY_SOCKS/src/main/java/Forwarder.java
> +        try (ServerSocketChannel ssChannel = ServerSocketChannel.open();
Подход неплох, но непонятно следующее: 
1. почему не работаем с data напрямую, а передаем ссылку на нее ?
2. Если все-таки делать так, как тут, то я бы добавил final блок и в нем проверку вроде такой: 
`if (udpsocket != null && udpsocket.isOpen) {`
 `udpsocket.close()`
`}`
`udpsocket = null;`

2019-01-03 05:50 UTC, Aloomenon commented
Заодно проверил на работоспособность. Вроде все ок, но один раз завалилось во время обновления страницы с ютубом. Трейс:
java.lang.ArrayIndexOutOfBoundsException: -3
	at MessageParser.getPort(MessageParser.java:73)
	at Forwarder.forward(Forwarder.java:107)
	at Main.main(Main.java:11)

2019-01-03 10:02 UTC, Aloomenon commented
Принято. Можно заливать в мастер.

2019-01-03 16:44 UTC, merged